"""Checks on the resume-kit shared data and the six skills that depend on it."""
import re
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

import _paths
from _paths import REPO

RK = REPO / "skills" / "resume-kit"
RESUME_SKILLS = ["make-resume", "make-cover-letter", "critique", "edit-resume", "setup-build-kb", "setup-extract"]


class ResumeKitContentTests(unittest.TestCase):
    def test_no_claude_md_or_hermes_references(self):
        for f in RK.rglob("*.md"):
            text = f.read_text(encoding="utf-8", errors="replace")
            self.assertNotIn("CLAUDE.md", text, f.relative_to(REPO))
            self.assertNotIn("hermes", text.lower(), f.relative_to(REPO))

    def test_generated_kb_files_not_shipped(self):
        # skills_taxonomy / pub_metadata / achievement_reframing_guide / significance_* are built by
        # setup-build-kb from cv_source, not shipped as static reference data.
        names = {p.name for p in (RK / "support").glob("*.md")}
        for bad in ("skills_taxonomy.md", "pub_metadata.md", "achievement_reframing_guide.md"):
            self.assertNotIn(bad, names)
        self.assertFalse(list((RK / "support").glob("significance_*.md")))

    def test_workflow_b_context_note_present(self):
        text = (RK / "reference" / "resume_reference.md").read_text()
        self.assertIn("Workflow B", text)
        self.assertIn("create-template", text)

    def test_tectonic_is_default_compiler(self):
        text = (RK / "reference" / "resume_reference.md").read_text()
        self.assertIn("tectonic", text)

    def test_shared_ops_points_at_workspace_sessions_and_core_sources(self):
        text = (RK / "reference" / "shared_ops.md").read_text()
        self.assertIn("<workspace>/SESSIONS.md", text)
        self.assertIn("OPERATIONS.md#sources", text)
        self.assertNotIn("https://cv.", text)  # no hard-coded live-source domain

    def test_fictional_examples_are_not_real(self):
        # the shipped example session/resume fixtures must be the fictional Whitfield set, not real data
        text = (RK / "examples" / "example_session_file.md").read_text()
        self.assertIn("Whitfield", text)


class ResumeSkillFrontmatterTests(unittest.TestCase):
    def test_name_matches_directory_and_requires_resume_kit(self):
        for skill in RESUME_SKILLS:
            d = REPO / "skills" / skill
            fm = (d / "SKILL.md").read_text()
            self.assertIn(f"name: {skill}", fm)
            reqs = (d / "requires.txt").read_text().split()
            self.assertIn("resume-kit", reqs)
            self.assertIn("humanizer", reqs)

    def test_no_bare_config_md_personal_info_pointer(self):
        # old-style bare pointers ("config.md Personal Info" etc.) must have been rewritten to
        # heading-qualified pointers so a reader knows which part of the single config file to open
        for skill in RESUME_SKILLS:
            text = (REPO / "skills" / skill / "SKILL.md").read_text()
            self.assertNotIn("config.md Provenance Flags", text)
            self.assertNotIn("config.md Personal Info", text)
            self.assertNotIn("CLAUDE.md", text)


class InstalledResumeSkillTests(unittest.TestCase):
    """Cross-skill token references resolve from the repo checkout (skills run in place)."""

    def test_char_count_reachable_via_token_resolution(self):
        text = (REPO / "skills" / "make-resume" / "SKILL.md").read_text()
        m = re.search(r"python3 (\S*helpers/char_count\.py)", text)
        self.assertIsNotNone(m)
        # OPERATIONS.md token rule: {{RESUME_KIT_DIR}} = <repo>/skills/resume-kit
        resolved = m.group(1).replace("{{RESUME_KIT_DIR}}", str(REPO / "skills" / "resume-kit"))
        helper = Path(resolved)
        self.assertTrue(helper.is_file(), helper)
        r2 = subprocess.run([sys.executable, str(helper), "--help"], capture_output=True, text=True)
        self.assertIn(r2.returncode, (0, 1, 2))  # just must run, not crash on import/path errors


class CreateTemplateSkeletonTests(unittest.TestCase):
    ASSETS = REPO / "skills" / "create-template" / "assets"

    def test_no_em_dash_as_a_token_separator(self):
        # A line like '\textbf{[[X]]} — [[Y]]' puts a real em-dash between two placeholders, so any
        # document generated by filling the tokens would ship with a banned em-dash (OPERATIONS
        # #format). Comments (%) are exempt since they never render.
        bad = re.compile(r"\]\]\}?\s*—|—\s*\[\[")
        for f in self.ASSETS.glob("*.tex"):
            for line in f.read_text(encoding="utf-8").splitlines():
                code = line.split("%", 1)[0]
                self.assertIsNone(bad.search(code), f"{f.name}: {line!r}")

    def test_skeletons_exist_for_all_three_document_types(self):
        names = {p.name for p in self.ASSETS.glob("*.tex")}
        self.assertEqual(names, {"CV_SKELETON.tex", "RESUME_SKELETON.tex", "CL_SKELETON.tex"})


class ResumeKitLineBreakHazardTests(unittest.TestCase):
    TEMPLATES = REPO / "skills" / "resume-kit" / "templates"

    def test_no_linebreak_before_bracket(self):
        # `\\` followed by `[` is parsed as an optional length argument, so a
        # line break before a bracketed placeholder ('...End]}\\\n[FIXED: ...'
        # or 'Sincerely,\\\n[Your Name]') fails with 'Missing number, treated
        # as zero'. The fix is `\\{}` (empty group blocks the parse, renders
        # identically). Legitimate lengths like `\\[1pt]` are allowed.
        # Comments (%) are exempt since they never render.
        inline_bad = re.compile(r"\\\\\[(?![\d.\-+\\])")
        for f in self.TEMPLATES.glob("*.tex"):
            lines = f.read_text(encoding="utf-8").splitlines()
            for i, line in enumerate(lines):
                code = line.split("%", 1)[0]
                self.assertIsNone(
                    inline_bad.search(code), f"{f.name}:{i + 1}: {line!r}")
                if re.search(r"\\\\\s*$", code) and i + 1 < len(lines):
                    nxt = lines[i + 1].split("%", 1)[0]
                    self.assertFalse(
                        re.match(r"\s*\[", nxt),
                        f"{f.name}:{i + 1} ends with \\\\ and next line "
                        f"starts with '[': {lines[i + 1]!r}")


if __name__ == "__main__":
    unittest.main()
